apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: signup-login-app
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data